server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3307/delivery_map # 데이터베이스 이름에 맞게 변경
    username: MAP_APP
    password: ${MAP_APP_PW}
jwt:
  secret: ${ENC_KEY}
  expiration: 10000
  refresh-expiration: 100000
