spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/DELIVERY_MAP # 데이터베이스 이름에 맞게 변경
    username: MAP_APP # MySQL 사용자 이름
    password: ${MAP_APP_PW} # MySQL 비밀번호
  jpa: # JPA를 직접 사용하지 않아도, DDL 자동 생성 등의 기능을 위해 필요할 수 있습니다.
    hibernate:
      ddl-auto: update # 개발 환경에서 스키마 자동 생성/업데이트 (운영 환경에서는 'none' 또는 'validate' 권장)
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅
    show-sql: true # 콘솔에 SQL 쿼리 출력
enc:
  key: %{ENC_KEY}}