spring:
  webflux:
    #base-path: /api # API 기본 URL
    #static-path-pattern: /static/**
    max-in-memory-size: 10MB #BodyExtractors를 사용할 때, 메모리로 읽을 수 있는 최대 바이트 수
  profiles:
    active: local
  r2dbc:
    pool:
      initial-size: 1 # 초기 커넥션 수
      max-size: 10 # 최대 커넥션 수
      max-idle-time: 30s # 커넥션 유휴 최대 시간
      max-create-connection-time: 5s #커넥션 생성 최대 허용 시간
server:
  port: 8080
logging:
  level:
     org.springframework.r2dbc.core: DEBUG # R2DBC SQL 로그 디버깅
