spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/delivery_map # 데이터베이스 이름에 맞게 변경
    username: MAP_APP
    password: ${MAP_APP_PW}
jwt:
  secret: ${ENC_KEY}
  expiration: 2 #150000 jwt 만료시간
  ref-expiration: 10 # 1050000 리프레쉬 토큰 만료 시간