version: '3.8'

services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/data:/data
      - ./redis/logs:/var/log/redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
